import{translations}from './translations.js';export class LanguageManager{constructor(){this.currentLang=localStorage.getItem('preferred-language');this.init()}
init(){if(!this.currentLang){this.showSplashScreen()}else{this.currentLang=this.currentLang||'en';this.updateUI()}
this.setupEventListeners()}
isMobile(){return window.innerWidth<=768}
showSplashScreen(){const splash=document.getElementById('languageSplash');if(splash){splash.style.display='flex';splash.offsetHeight;splash.classList.add('active');splash.querySelectorAll('.splash-lang-btn').forEach(btn=>{btn.addEventListener('click',(e)=>{const lang=e.target.closest('.splash-lang-btn').dataset.lang;this.setLanguage(lang);splash.classList.remove('active');setTimeout(()=>{splash.style.display='none'},300)})})}}
setupEventListeners(){document.querySelectorAll('.lang-btn').forEach(btn=>{btn.addEventListener('click',(e)=>{const newLang=e.target.dataset.lang;this.setLanguage(newLang)})})}
setLanguage(lang){this.currentLang=lang;localStorage.setItem('preferred-language',lang);document.documentElement.lang=lang;this.updateUI()}
updateUI(){const t=translations[this.currentLang];document.querySelectorAll('.lang-btn').forEach(btn=>{btn.classList.toggle('active',btn.dataset.lang===this.currentLang)});this.updateElement('a[href="#products"]',t.nav.products);this.updateElement('a[href="#brands"]',t.nav.brands);this.updateElement('a[href="#reviews"]',t.nav.reviews);this.updateElement('a[href="#contact"]',t.nav.contact);this.updateElement('.hero__title',t.hero.title);this.updateElement('.hero__subtitle',t.hero.subtitle);this.updateElement('.cta-button--primary',t.hero.cta.shop);this.updateElement('.cta-button--secondary',t.hero.cta.find);this.updateElement('.search .section-title',t.search.title);this.updateElement('#make option:first-child',t.search.make);this.updateElement('#model option:first-child',t.search.model);this.updateElement('#year option:first-child',t.search.year);this.updateElement('#engine option:first-child',t.search.engine);this.updateElement('#category option:first-child',t.search.category);this.updateElement('.search__button',t.search.button);this.updateElement('.products .section-title',t.products.title);document.querySelectorAll('.product-card').forEach(card=>{const title=card.querySelector('.product-card__title');const addToCart=card.querySelector('.btn--primary');const viewDetails=card.querySelector('.btn--secondary');const badge=card.querySelector('.product-card__badge');const reviews=card.querySelector('.product-card__rating span');if(title)title.textContent=t.products[card.dataset.productKey]||title.textContent;if(addToCart)addToCart.textContent=t.products.addToCart;if(viewDetails)viewDetails.textContent=t.products.viewDetails;if(badge){if(badge.textContent.includes('%')){const discount=badge.textContent.match(/\d+/)[0];badge.textContent=t.products.discount.replace('{discount}',discount)}else if(badge.textContent==='NEW'){badge.textContent=t.products.new}else if(badge.textContent==='HOT'){badge.textContent=t.products.hot}}
if(reviews){const count=reviews.textContent.match(/\d+/)[0];reviews.textContent=`(${count} ${t.products.reviews})`}});Object.keys(t.features).forEach(key=>{this.updateElement(`.feature-${key} .feature__title`,t.features[key].title);this.updateElement(`.feature-${key} .feature__desc`,t.features[key].desc)});this.updateElement('.footer__quickLinks',t.footer.quickLinks);this.updateElement('.footer__shop',t.footer.shop);this.updateElement('.footer__about',t.footer.about);this.updateElement('.footer__contact',t.footer.contact);this.updateElement('.footer__support',t.footer.support);this.updateElement('.footer__faq',t.footer.faq);this.updateElement('.footer__shipping',t.footer.shipping);this.updateElement('.footer__returns',t.footer.returns);this.updateElement('.footer__newsletter',t.footer.newsletter);this.updateElement('.footer__subscribe',t.footer.subscribe);const emailInput=document.querySelector('.footer__emailPlaceholder');if(emailInput){emailInput.placeholder=t.footer.emailPlaceholder}}
updateElement(selector,text){const element=document.querySelector(selector);if(element){element.textContent=text}}}